### ISSUE TITLE
Clarify virtual browser context group id diagrams

### ISSUE THREAD

**Issue by arturjanc** [camillelamy/explainers#13]
In this section https://github.com/camillelamy/explainers/blob/master/coop_reporting.md#virtual-browsing-context-group-id:

I understand the behavior of the first two, but I'm lost on diagrams 3 and 4. Specifically, why is there a BCG switch after the first navigation (BCG4 to BCG2)? Also, why is the first window in BCG4?

I expect this is correct and I'm just missing something; maybe it would be helpful to explain the interactions that are happening below each diagram?

**Comment by camillelamy** [comment]
I have added a legend. Basically, the first page decides to navigate to the same URL it opened, and COOP enforcement would put the two in different browsing context group since there are two switches happening and each one put the page in a brand new BCG.

**Comment by arturjanc** [comment]
Thanks! Now I see that my confusion was that I was looking at the diagrams as if they were 4 individual examples, whereas from your legend it's clear that it's a single scenario where different windows are navigated in each subsequent step.
