### ISSUE TITLE
Anonymous iframe: credentials attribute

### ISSUE THREAD

**Issue by antosart** [camillelamy/explainers#20]
What is the semantic of the `credentials` attribute? `credentials=omit` vs `credentials=present` doesn't look good because of inconsistency (`omit` is a verb, while `present` is an adjective). In case, I'd suggest having `credentials=use` instead.

However, I am a bit unhappy with `credentials=omit` since this is misleading. Credentials are partitioned, not omitted. Moreover, I don't see the point of having a non-boolean attribute for something that can only be set and not unset (`credentials=use` - if we go with it - has no point of existing, apart from giving a value to be returned by the getter, since a subframe of an anonymous iframe is always anonymous and this cannot be overwritten).

I would reconsider having a boolean attribute instead, something like `<iframe anonymous>` or `<iframe partitioned>` or `<iframe isolated>` or `<iframe partitioned-storage>` or `<iframe clean-credentials>` (I fear none of these is a particularly good choice though).

**Comment by ArthurSonzogni** [comment]
Explainer updated from:
```html
<iframe credentials=omit>
```
toward
```html
<iframe anonymous>
```
in PR:
https://github.com/ArthurSonzogni/explainers/commit/5d12c9aeb8481736f16fcc91875816afbcece6d4

So we can close this, I guess, once it is merged.

**Comment by ArthurSonzogni** [comment]
@camillelamy: can we close this?

**Comment by camillelamy** [comment]
Done.

**Comment by Keepitsolid38** [comment]
Credintials=hbic
