### ISSUE TITLE
[COOP Reporting] Questions about the report body

### ISSUE THREAD

**Issue by domenic** [camillelamy/explainers#3]
https://github.com/camillelamy/explainers/blob/master/coop_reporting.md#reporting-browsing-context-switches

- Some of these keys contain spaces. Is that intentional? JSON objects are usually underscore-delimited
- uri should be url, per https://url.spec.whatwg.org/#url-apis-elsewhere
- I'm unsure about the "disposition" field. COEP reporting does not include something similar, but I think CSP does. @yutakahirano, should these be aligned?
- "Note that effective policy can be same-origin-plus-coep". In the HTML PR we spelled this with a capital COEP. Maybe we should correct the HTML PR to align the casing, either now or when we work on reporting.

**Comment by domenic** [comment]
I see "disposition" is planned for COEP in https://github.com/whatwg/html/issues/5391. Also I found https://github.com/WICG/cross-origin-embedder-policy/pull/9#discussion_r387513989 which indicates that maybe reporting object fields are neither space nor underscore delimited, but instead dash delimited.

**Comment by camillelamy** [comment]
I have updated the explainer and this should now be fixed.
